Added check to see if pulumi cli is installed and added condition to install it only if it is missing

diff --git a/.github/workflows/deploy-pulumi.yml b/.github/workflows/deploy-pulumi.yml
--- a/.github/workflows/deploy-pulumi.yml
+++ b/.github/workflows/deploy-pulumi.yml
@@ -33,7 +33,12 @@ jobs:
         with:
           creds: ${{ secrets.AZURE_CREDENTIALS }}
 
+      - name: Check if Pulumi CLI is installed
+        id: pulumi-check
+        run: pulumi version || echo "Pulumi CLI not found"
+
       - name: Install Pulumi CLI
+        if: steps.pulumi-check.outcome == 'failure'
         run: |
           curl -fsSL https://get.pulumi.com | sh
           echo "$HOME/.pulumi/bin" >> $GITHUB_PATH
